from turtle import *
from random import randint
penup()
goto(-100,100)
pendown()
write("Guess\nThe quantity\n(In percents)", font=("times",8))
pen(pensize=5)
hideturtle()
right(90)
forward(100)
left(90)
forward(50)
left(90)
forward(100)
right(180)
N=randint(2,100)
pen(pensize=1)
penup()
forward(100-N)
right(90)
pendown()
color("lightblue")
begin_fill()
forward(50)
left(90)
forward(N)
left(90)
forward(50)
left(90)
forward(N)
end_fill()
penup()
goto(-100,-100)
pendown()
U=numinput("Guess The Quantity", "Your Guessing", minval=1, maxval=100)
if U == N:
	color("red")
	write("Epic Guessing!\nQuantity was "+str(N)+"%")
elif U in range(N-3, N+4):
	color("blue")
	write("Great Guessing!\nQuantity was "+str(N)+"%")
elif U in range(N-5, N+6):
	color("green")
	write("Excellent Guessing!\nQuantity was "+str(N)+"%")
elif U in range(N-8, N+9):
	color("lightgreen")
	write("Good Guessing!\nQuantity was "+str(N)+"%")
else:
	color("orange")
	write("Bad Guessing :(\nQuantity was "+str(N)+"%")
exitonclick()